// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protobuf/message.proto

package com.netty.example.seventhexample.multimsg.proto;

public interface AppOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xu.netty.seventhexample.multimsg.proto.App)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string ip = 1;</code>
   * @return Whether the ip field is set.
   */
  boolean hasIp();
  /**
   * <code>optional string ip = 1;</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <code>optional string ip = 1;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>optional string phoneType = 2;</code>
   * @return Whether the phoneType field is set.
   */
  boolean hasPhoneType();
  /**
   * <code>optional string phoneType = 2;</code>
   * @return The phoneType.
   */
  java.lang.String getPhoneType();
  /**
   * <code>optional string phoneType = 2;</code>
   * @return The bytes for phoneType.
   */
  com.google.protobuf.ByteString
      getPhoneTypeBytes();
}
