// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protobuf/message.proto

package com.netty.example.seventhexample.multimsg.proto;

public interface PadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xu.netty.seventhexample.multimsg.proto.Pad)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string ip = 1;</code>
   * @return Whether the ip field is set.
   */
  boolean hasIp();
  /**
   * <code>optional string ip = 1;</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <code>optional string ip = 1;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>optional string padType = 2;</code>
   * @return Whether the padType field is set.
   */
  boolean hasPadType();
  /**
   * <code>optional string padType = 2;</code>
   * @return The padType.
   */
  java.lang.String getPadType();
  /**
   * <code>optional string padType = 2;</code>
   * @return The bytes for padType.
   */
  com.google.protobuf.ByteString
      getPadTypeBytes();
}
