// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protobuf/message.proto

package com.xu.netty.seventhexample.multimsg.proto;

public interface ComputerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xu.netty.seventhexample.multimsg.proto.Computer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string ip = 1;</code>
   * @return Whether the ip field is set.
   */
  boolean hasIp();
  /**
   * <code>optional string ip = 1;</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <code>optional string ip = 1;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>optional string computerType = 2;</code>
   * @return Whether the computerType field is set.
   */
  boolean hasComputerType();
  /**
   * <code>optional string computerType = 2;</code>
   * @return The computerType.
   */
  java.lang.String getComputerType();
  /**
   * <code>optional string computerType = 2;</code>
   * @return The bytes for computerType.
   */
  com.google.protobuf.ByteString
      getComputerTypeBytes();
}
