// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protobuf/message.proto

package com.xu.netty.seventhexample.multimsg.proto;

/**
 * Protobuf type {@code com.xu.netty.seventhexample.multimsg.proto.MyMessage}
 */
public  final class MyMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.xu.netty.seventhexample.multimsg.proto.MyMessage)
    MyMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MyMessage.newBuilder() to construct.
  private MyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MyMessage() {
    type_ = 1;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MyMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MyMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            com.xu.netty.seventhexample.multimsg.proto.MyMessage.MessageType value = com.xu.netty.seventhexample.multimsg.proto.MyMessage.MessageType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(1, rawValue);
            } else {
              bitField0_ |= 0x00000001;
              type_ = rawValue;
            }
            break;
          }
          case 18: {
            com.xu.netty.seventhexample.multimsg.proto.App.Builder subBuilder = null;
            if (bodyCase_ == 2) {
              subBuilder = ((com.xu.netty.seventhexample.multimsg.proto.App) body_).toBuilder();
            }
            body_ =
                input.readMessage(com.xu.netty.seventhexample.multimsg.proto.App.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.xu.netty.seventhexample.multimsg.proto.App) body_);
              body_ = subBuilder.buildPartial();
            }
            bodyCase_ = 2;
            break;
          }
          case 26: {
            com.xu.netty.seventhexample.multimsg.proto.Pad.Builder subBuilder = null;
            if (bodyCase_ == 3) {
              subBuilder = ((com.xu.netty.seventhexample.multimsg.proto.Pad) body_).toBuilder();
            }
            body_ =
                input.readMessage(com.xu.netty.seventhexample.multimsg.proto.Pad.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.xu.netty.seventhexample.multimsg.proto.Pad) body_);
              body_ = subBuilder.buildPartial();
            }
            bodyCase_ = 3;
            break;
          }
          case 34: {
            com.xu.netty.seventhexample.multimsg.proto.Computer.Builder subBuilder = null;
            if (bodyCase_ == 4) {
              subBuilder = ((com.xu.netty.seventhexample.multimsg.proto.Computer) body_).toBuilder();
            }
            body_ =
                input.readMessage(com.xu.netty.seventhexample.multimsg.proto.Computer.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.xu.netty.seventhexample.multimsg.proto.Computer) body_);
              body_ = subBuilder.buildPartial();
            }
            bodyCase_ = 4;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xu.netty.seventhexample.multimsg.proto.MyClientInfo.internal_static_com_xu_netty_seventhexample_multimsg_proto_MyMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xu.netty.seventhexample.multimsg.proto.MyClientInfo.internal_static_com_xu_netty_seventhexample_multimsg_proto_MyMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xu.netty.seventhexample.multimsg.proto.MyMessage.class, com.xu.netty.seventhexample.multimsg.proto.MyMessage.Builder.class);
  }

  /**
   * Protobuf enum {@code com.xu.netty.seventhexample.multimsg.proto.MyMessage.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>App = 1;</code>
     */
    App(1),
    /**
     * <code>Pad = 2;</code>
     */
    Pad(2),
    /**
     * <code>Computer = 3;</code>
     */
    Computer(3),
    ;

    /**
     * <code>App = 1;</code>
     */
    public static final int App_VALUE = 1;
    /**
     * <code>Pad = 2;</code>
     */
    public static final int Pad_VALUE = 2;
    /**
     * <code>Computer = 3;</code>
     */
    public static final int Computer_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MessageType forNumber(int value) {
      switch (value) {
        case 1: return App;
        case 2: return Pad;
        case 3: return Computer;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.xu.netty.seventhexample.multimsg.proto.MyMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.xu.netty.seventhexample.multimsg.proto.MyMessage.MessageType)
  }

  private int bitField0_;
  private int bodyCase_ = 0;
  private java.lang.Object body_;
  public enum BodyCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    APP(2),
    PAD(3),
    COMPUTER(4),
    BODY_NOT_SET(0);
    private final int value;
    private BodyCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BodyCase valueOf(int value) {
      return forNumber(value);
    }

    public static BodyCase forNumber(int value) {
      switch (value) {
        case 2: return APP;
        case 3: return PAD;
        case 4: return COMPUTER;
        case 0: return BODY_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public BodyCase
  getBodyCase() {
    return BodyCase.forNumber(
        bodyCase_);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>required .com.xu.netty.seventhexample.multimsg.proto.MyMessage.MessageType type = 1;</code>
   * @return Whether the type field is set.
   */
  public boolean hasType() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required .com.xu.netty.seventhexample.multimsg.proto.MyMessage.MessageType type = 1;</code>
   * @return The type.
   */
  public com.xu.netty.seventhexample.multimsg.proto.MyMessage.MessageType getType() {
    @SuppressWarnings("deprecation")
    com.xu.netty.seventhexample.multimsg.proto.MyMessage.MessageType result = com.xu.netty.seventhexample.multimsg.proto.MyMessage.MessageType.valueOf(type_);
    return result == null ? com.xu.netty.seventhexample.multimsg.proto.MyMessage.MessageType.App : result;
  }

  public static final int APP_FIELD_NUMBER = 2;
  /**
   * <code>optional .com.xu.netty.seventhexample.multimsg.proto.App app = 2;</code>
   * @return Whether the app field is set.
   */
  public boolean hasApp() {
    return bodyCase_ == 2;
  }
  /**
   * <code>optional .com.xu.netty.seventhexample.multimsg.proto.App app = 2;</code>
   * @return The app.
   */
  public com.xu.netty.seventhexample.multimsg.proto.App getApp() {
    if (bodyCase_ == 2) {
       return (com.xu.netty.seventhexample.multimsg.proto.App) body_;
    }
    return com.xu.netty.seventhexample.multimsg.proto.App.getDefaultInstance();
  }
  /**
   * <code>optional .com.xu.netty.seventhexample.multimsg.proto.App app = 2;</code>
   */
  public com.xu.netty.seventhexample.multimsg.proto.AppOrBuilder getAppOrBuilder() {
    if (bodyCase_ == 2) {
       return (com.xu.netty.seventhexample.multimsg.proto.App) body_;
    }
    return com.xu.netty.seventhexample.multimsg.proto.App.getDefaultInstance();
  }

  public static final int PAD_FIELD_NUMBER = 3;
  /**
   * <code>optional .com.xu.netty.seventhexample.multimsg.proto.Pad pad = 3;</code>
   * @return Whether the pad field is set.
   */
  public boolean hasPad() {
    return bodyCase_ == 3;
  }
  /**
   * <code>optional .com.xu.netty.seventhexample.multimsg.proto.Pad pad = 3;</code>
   * @return The pad.
   */
  public com.xu.netty.seventhexample.multimsg.proto.Pad getPad() {
    if (bodyCase_ == 3) {
       return (com.xu.netty.seventhexample.multimsg.proto.Pad) body_;
    }
    return com.xu.netty.seventhexample.multimsg.proto.Pad.getDefaultInstance();
  }
  /**
   * <code>optional .com.xu.netty.seventhexample.multimsg.proto.Pad pad = 3;</code>
   */
  public com.xu.netty.seventhexample.multimsg.proto.PadOrBuilder getPadOrBuilder() {
    if (bodyCase_ == 3) {
       return (com.xu.netty.seventhexample.multimsg.proto.Pad) body_;
    }
    return com.xu.netty.seventhexample.multimsg.proto.Pad.getDefaultInstance();
  }

  public static final int COMPUTER_FIELD_NUMBER = 4;
  /**
   * <code>optional .com.xu.netty.seventhexample.multimsg.proto.Computer computer = 4;</code>
   * @return Whether the computer field is set.
   */
  public boolean hasComputer() {
    return bodyCase_ == 4;
  }
  /**
   * <code>optional .com.xu.netty.seventhexample.multimsg.proto.Computer computer = 4;</code>
   * @return The computer.
   */
  public com.xu.netty.seventhexample.multimsg.proto.Computer getComputer() {
    if (bodyCase_ == 4) {
       return (com.xu.netty.seventhexample.multimsg.proto.Computer) body_;
    }
    return com.xu.netty.seventhexample.multimsg.proto.Computer.getDefaultInstance();
  }
  /**
   * <code>optional .com.xu.netty.seventhexample.multimsg.proto.Computer computer = 4;</code>
   */
  public com.xu.netty.seventhexample.multimsg.proto.ComputerOrBuilder getComputerOrBuilder() {
    if (bodyCase_ == 4) {
       return (com.xu.netty.seventhexample.multimsg.proto.Computer) body_;
    }
    return com.xu.netty.seventhexample.multimsg.proto.Computer.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(1, type_);
    }
    if (bodyCase_ == 2) {
      output.writeMessage(2, (com.xu.netty.seventhexample.multimsg.proto.App) body_);
    }
    if (bodyCase_ == 3) {
      output.writeMessage(3, (com.xu.netty.seventhexample.multimsg.proto.Pad) body_);
    }
    if (bodyCase_ == 4) {
      output.writeMessage(4, (com.xu.netty.seventhexample.multimsg.proto.Computer) body_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (bodyCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.xu.netty.seventhexample.multimsg.proto.App) body_);
    }
    if (bodyCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.xu.netty.seventhexample.multimsg.proto.Pad) body_);
    }
    if (bodyCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.xu.netty.seventhexample.multimsg.proto.Computer) body_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xu.netty.seventhexample.multimsg.proto.MyMessage)) {
      return super.equals(obj);
    }
    com.xu.netty.seventhexample.multimsg.proto.MyMessage other = (com.xu.netty.seventhexample.multimsg.proto.MyMessage) obj;

    if (hasType() != other.hasType()) return false;
    if (hasType()) {
      if (type_ != other.type_) return false;
    }
    if (!getBodyCase().equals(other.getBodyCase())) return false;
    switch (bodyCase_) {
      case 2:
        if (!getApp()
            .equals(other.getApp())) return false;
        break;
      case 3:
        if (!getPad()
            .equals(other.getPad())) return false;
        break;
      case 4:
        if (!getComputer()
            .equals(other.getComputer())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasType()) {
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
    }
    switch (bodyCase_) {
      case 2:
        hash = (37 * hash) + APP_FIELD_NUMBER;
        hash = (53 * hash) + getApp().hashCode();
        break;
      case 3:
        hash = (37 * hash) + PAD_FIELD_NUMBER;
        hash = (53 * hash) + getPad().hashCode();
        break;
      case 4:
        hash = (37 * hash) + COMPUTER_FIELD_NUMBER;
        hash = (53 * hash) + getComputer().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xu.netty.seventhexample.multimsg.proto.MyMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xu.netty.seventhexample.multimsg.proto.MyMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xu.netty.seventhexample.multimsg.proto.MyMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xu.netty.seventhexample.multimsg.proto.MyMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xu.netty.seventhexample.multimsg.proto.MyMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xu.netty.seventhexample.multimsg.proto.MyMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xu.netty.seventhexample.multimsg.proto.MyMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xu.netty.seventhexample.multimsg.proto.MyMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xu.netty.seventhexample.multimsg.proto.MyMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xu.netty.seventhexample.multimsg.proto.MyMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xu.netty.seventhexample.multimsg.proto.MyMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xu.netty.seventhexample.multimsg.proto.MyMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xu.netty.seventhexample.multimsg.proto.MyMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.xu.netty.seventhexample.multimsg.proto.MyMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.xu.netty.seventhexample.multimsg.proto.MyMessage)
      com.xu.netty.seventhexample.multimsg.proto.MyMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xu.netty.seventhexample.multimsg.proto.MyClientInfo.internal_static_com_xu_netty_seventhexample_multimsg_proto_MyMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xu.netty.seventhexample.multimsg.proto.MyClientInfo.internal_static_com_xu_netty_seventhexample_multimsg_proto_MyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xu.netty.seventhexample.multimsg.proto.MyMessage.class, com.xu.netty.seventhexample.multimsg.proto.MyMessage.Builder.class);
    }

    // Construct using com.xu.netty.seventhexample.multimsg.proto.MyMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = 1;
      bitField0_ = (bitField0_ & ~0x00000001);
      bodyCase_ = 0;
      body_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xu.netty.seventhexample.multimsg.proto.MyClientInfo.internal_static_com_xu_netty_seventhexample_multimsg_proto_MyMessage_descriptor;
    }

    @java.lang.Override
    public com.xu.netty.seventhexample.multimsg.proto.MyMessage getDefaultInstanceForType() {
      return com.xu.netty.seventhexample.multimsg.proto.MyMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.xu.netty.seventhexample.multimsg.proto.MyMessage build() {
      com.xu.netty.seventhexample.multimsg.proto.MyMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xu.netty.seventhexample.multimsg.proto.MyMessage buildPartial() {
      com.xu.netty.seventhexample.multimsg.proto.MyMessage result = new com.xu.netty.seventhexample.multimsg.proto.MyMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.type_ = type_;
      if (bodyCase_ == 2) {
        if (appBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = appBuilder_.build();
        }
      }
      if (bodyCase_ == 3) {
        if (padBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = padBuilder_.build();
        }
      }
      if (bodyCase_ == 4) {
        if (computerBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = computerBuilder_.build();
        }
      }
      result.bitField0_ = to_bitField0_;
      result.bodyCase_ = bodyCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xu.netty.seventhexample.multimsg.proto.MyMessage) {
        return mergeFrom((com.xu.netty.seventhexample.multimsg.proto.MyMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xu.netty.seventhexample.multimsg.proto.MyMessage other) {
      if (other == com.xu.netty.seventhexample.multimsg.proto.MyMessage.getDefaultInstance()) return this;
      if (other.hasType()) {
        setType(other.getType());
      }
      switch (other.getBodyCase()) {
        case APP: {
          mergeApp(other.getApp());
          break;
        }
        case PAD: {
          mergePad(other.getPad());
          break;
        }
        case COMPUTER: {
          mergeComputer(other.getComputer());
          break;
        }
        case BODY_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasType()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xu.netty.seventhexample.multimsg.proto.MyMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xu.netty.seventhexample.multimsg.proto.MyMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bodyCase_ = 0;
    private java.lang.Object body_;
    public BodyCase
        getBodyCase() {
      return BodyCase.forNumber(
          bodyCase_);
    }

    public Builder clearBody() {
      bodyCase_ = 0;
      body_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private int type_ = 1;
    /**
     * <code>required .com.xu.netty.seventhexample.multimsg.proto.MyMessage.MessageType type = 1;</code>
     * @return Whether the type field is set.
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .com.xu.netty.seventhexample.multimsg.proto.MyMessage.MessageType type = 1;</code>
     * @return The type.
     */
    public com.xu.netty.seventhexample.multimsg.proto.MyMessage.MessageType getType() {
      @SuppressWarnings("deprecation")
      com.xu.netty.seventhexample.multimsg.proto.MyMessage.MessageType result = com.xu.netty.seventhexample.multimsg.proto.MyMessage.MessageType.valueOf(type_);
      return result == null ? com.xu.netty.seventhexample.multimsg.proto.MyMessage.MessageType.App : result;
    }
    /**
     * <code>required .com.xu.netty.seventhexample.multimsg.proto.MyMessage.MessageType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.xu.netty.seventhexample.multimsg.proto.MyMessage.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>required .com.xu.netty.seventhexample.multimsg.proto.MyMessage.MessageType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 1;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.xu.netty.seventhexample.multimsg.proto.App, com.xu.netty.seventhexample.multimsg.proto.App.Builder, com.xu.netty.seventhexample.multimsg.proto.AppOrBuilder> appBuilder_;
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.App app = 2;</code>
     * @return Whether the app field is set.
     */
    public boolean hasApp() {
      return bodyCase_ == 2;
    }
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.App app = 2;</code>
     * @return The app.
     */
    public com.xu.netty.seventhexample.multimsg.proto.App getApp() {
      if (appBuilder_ == null) {
        if (bodyCase_ == 2) {
          return (com.xu.netty.seventhexample.multimsg.proto.App) body_;
        }
        return com.xu.netty.seventhexample.multimsg.proto.App.getDefaultInstance();
      } else {
        if (bodyCase_ == 2) {
          return appBuilder_.getMessage();
        }
        return com.xu.netty.seventhexample.multimsg.proto.App.getDefaultInstance();
      }
    }
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.App app = 2;</code>
     */
    public Builder setApp(com.xu.netty.seventhexample.multimsg.proto.App value) {
      if (appBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        appBuilder_.setMessage(value);
      }
      bodyCase_ = 2;
      return this;
    }
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.App app = 2;</code>
     */
    public Builder setApp(
        com.xu.netty.seventhexample.multimsg.proto.App.Builder builderForValue) {
      if (appBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        appBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 2;
      return this;
    }
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.App app = 2;</code>
     */
    public Builder mergeApp(com.xu.netty.seventhexample.multimsg.proto.App value) {
      if (appBuilder_ == null) {
        if (bodyCase_ == 2 &&
            body_ != com.xu.netty.seventhexample.multimsg.proto.App.getDefaultInstance()) {
          body_ = com.xu.netty.seventhexample.multimsg.proto.App.newBuilder((com.xu.netty.seventhexample.multimsg.proto.App) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 2) {
          appBuilder_.mergeFrom(value);
        }
        appBuilder_.setMessage(value);
      }
      bodyCase_ = 2;
      return this;
    }
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.App app = 2;</code>
     */
    public Builder clearApp() {
      if (appBuilder_ == null) {
        if (bodyCase_ == 2) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 2) {
          bodyCase_ = 0;
          body_ = null;
        }
        appBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.App app = 2;</code>
     */
    public com.xu.netty.seventhexample.multimsg.proto.App.Builder getAppBuilder() {
      return getAppFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.App app = 2;</code>
     */
    public com.xu.netty.seventhexample.multimsg.proto.AppOrBuilder getAppOrBuilder() {
      if ((bodyCase_ == 2) && (appBuilder_ != null)) {
        return appBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 2) {
          return (com.xu.netty.seventhexample.multimsg.proto.App) body_;
        }
        return com.xu.netty.seventhexample.multimsg.proto.App.getDefaultInstance();
      }
    }
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.App app = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xu.netty.seventhexample.multimsg.proto.App, com.xu.netty.seventhexample.multimsg.proto.App.Builder, com.xu.netty.seventhexample.multimsg.proto.AppOrBuilder> 
        getAppFieldBuilder() {
      if (appBuilder_ == null) {
        if (!(bodyCase_ == 2)) {
          body_ = com.xu.netty.seventhexample.multimsg.proto.App.getDefaultInstance();
        }
        appBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xu.netty.seventhexample.multimsg.proto.App, com.xu.netty.seventhexample.multimsg.proto.App.Builder, com.xu.netty.seventhexample.multimsg.proto.AppOrBuilder>(
                (com.xu.netty.seventhexample.multimsg.proto.App) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 2;
      onChanged();;
      return appBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.xu.netty.seventhexample.multimsg.proto.Pad, com.xu.netty.seventhexample.multimsg.proto.Pad.Builder, com.xu.netty.seventhexample.multimsg.proto.PadOrBuilder> padBuilder_;
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.Pad pad = 3;</code>
     * @return Whether the pad field is set.
     */
    public boolean hasPad() {
      return bodyCase_ == 3;
    }
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.Pad pad = 3;</code>
     * @return The pad.
     */
    public com.xu.netty.seventhexample.multimsg.proto.Pad getPad() {
      if (padBuilder_ == null) {
        if (bodyCase_ == 3) {
          return (com.xu.netty.seventhexample.multimsg.proto.Pad) body_;
        }
        return com.xu.netty.seventhexample.multimsg.proto.Pad.getDefaultInstance();
      } else {
        if (bodyCase_ == 3) {
          return padBuilder_.getMessage();
        }
        return com.xu.netty.seventhexample.multimsg.proto.Pad.getDefaultInstance();
      }
    }
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.Pad pad = 3;</code>
     */
    public Builder setPad(com.xu.netty.seventhexample.multimsg.proto.Pad value) {
      if (padBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        padBuilder_.setMessage(value);
      }
      bodyCase_ = 3;
      return this;
    }
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.Pad pad = 3;</code>
     */
    public Builder setPad(
        com.xu.netty.seventhexample.multimsg.proto.Pad.Builder builderForValue) {
      if (padBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        padBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 3;
      return this;
    }
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.Pad pad = 3;</code>
     */
    public Builder mergePad(com.xu.netty.seventhexample.multimsg.proto.Pad value) {
      if (padBuilder_ == null) {
        if (bodyCase_ == 3 &&
            body_ != com.xu.netty.seventhexample.multimsg.proto.Pad.getDefaultInstance()) {
          body_ = com.xu.netty.seventhexample.multimsg.proto.Pad.newBuilder((com.xu.netty.seventhexample.multimsg.proto.Pad) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 3) {
          padBuilder_.mergeFrom(value);
        }
        padBuilder_.setMessage(value);
      }
      bodyCase_ = 3;
      return this;
    }
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.Pad pad = 3;</code>
     */
    public Builder clearPad() {
      if (padBuilder_ == null) {
        if (bodyCase_ == 3) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 3) {
          bodyCase_ = 0;
          body_ = null;
        }
        padBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.Pad pad = 3;</code>
     */
    public com.xu.netty.seventhexample.multimsg.proto.Pad.Builder getPadBuilder() {
      return getPadFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.Pad pad = 3;</code>
     */
    public com.xu.netty.seventhexample.multimsg.proto.PadOrBuilder getPadOrBuilder() {
      if ((bodyCase_ == 3) && (padBuilder_ != null)) {
        return padBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 3) {
          return (com.xu.netty.seventhexample.multimsg.proto.Pad) body_;
        }
        return com.xu.netty.seventhexample.multimsg.proto.Pad.getDefaultInstance();
      }
    }
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.Pad pad = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xu.netty.seventhexample.multimsg.proto.Pad, com.xu.netty.seventhexample.multimsg.proto.Pad.Builder, com.xu.netty.seventhexample.multimsg.proto.PadOrBuilder> 
        getPadFieldBuilder() {
      if (padBuilder_ == null) {
        if (!(bodyCase_ == 3)) {
          body_ = com.xu.netty.seventhexample.multimsg.proto.Pad.getDefaultInstance();
        }
        padBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xu.netty.seventhexample.multimsg.proto.Pad, com.xu.netty.seventhexample.multimsg.proto.Pad.Builder, com.xu.netty.seventhexample.multimsg.proto.PadOrBuilder>(
                (com.xu.netty.seventhexample.multimsg.proto.Pad) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 3;
      onChanged();;
      return padBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.xu.netty.seventhexample.multimsg.proto.Computer, com.xu.netty.seventhexample.multimsg.proto.Computer.Builder, com.xu.netty.seventhexample.multimsg.proto.ComputerOrBuilder> computerBuilder_;
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.Computer computer = 4;</code>
     * @return Whether the computer field is set.
     */
    public boolean hasComputer() {
      return bodyCase_ == 4;
    }
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.Computer computer = 4;</code>
     * @return The computer.
     */
    public com.xu.netty.seventhexample.multimsg.proto.Computer getComputer() {
      if (computerBuilder_ == null) {
        if (bodyCase_ == 4) {
          return (com.xu.netty.seventhexample.multimsg.proto.Computer) body_;
        }
        return com.xu.netty.seventhexample.multimsg.proto.Computer.getDefaultInstance();
      } else {
        if (bodyCase_ == 4) {
          return computerBuilder_.getMessage();
        }
        return com.xu.netty.seventhexample.multimsg.proto.Computer.getDefaultInstance();
      }
    }
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.Computer computer = 4;</code>
     */
    public Builder setComputer(com.xu.netty.seventhexample.multimsg.proto.Computer value) {
      if (computerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        computerBuilder_.setMessage(value);
      }
      bodyCase_ = 4;
      return this;
    }
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.Computer computer = 4;</code>
     */
    public Builder setComputer(
        com.xu.netty.seventhexample.multimsg.proto.Computer.Builder builderForValue) {
      if (computerBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        computerBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 4;
      return this;
    }
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.Computer computer = 4;</code>
     */
    public Builder mergeComputer(com.xu.netty.seventhexample.multimsg.proto.Computer value) {
      if (computerBuilder_ == null) {
        if (bodyCase_ == 4 &&
            body_ != com.xu.netty.seventhexample.multimsg.proto.Computer.getDefaultInstance()) {
          body_ = com.xu.netty.seventhexample.multimsg.proto.Computer.newBuilder((com.xu.netty.seventhexample.multimsg.proto.Computer) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 4) {
          computerBuilder_.mergeFrom(value);
        }
        computerBuilder_.setMessage(value);
      }
      bodyCase_ = 4;
      return this;
    }
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.Computer computer = 4;</code>
     */
    public Builder clearComputer() {
      if (computerBuilder_ == null) {
        if (bodyCase_ == 4) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 4) {
          bodyCase_ = 0;
          body_ = null;
        }
        computerBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.Computer computer = 4;</code>
     */
    public com.xu.netty.seventhexample.multimsg.proto.Computer.Builder getComputerBuilder() {
      return getComputerFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.Computer computer = 4;</code>
     */
    public com.xu.netty.seventhexample.multimsg.proto.ComputerOrBuilder getComputerOrBuilder() {
      if ((bodyCase_ == 4) && (computerBuilder_ != null)) {
        return computerBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 4) {
          return (com.xu.netty.seventhexample.multimsg.proto.Computer) body_;
        }
        return com.xu.netty.seventhexample.multimsg.proto.Computer.getDefaultInstance();
      }
    }
    /**
     * <code>optional .com.xu.netty.seventhexample.multimsg.proto.Computer computer = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xu.netty.seventhexample.multimsg.proto.Computer, com.xu.netty.seventhexample.multimsg.proto.Computer.Builder, com.xu.netty.seventhexample.multimsg.proto.ComputerOrBuilder> 
        getComputerFieldBuilder() {
      if (computerBuilder_ == null) {
        if (!(bodyCase_ == 4)) {
          body_ = com.xu.netty.seventhexample.multimsg.proto.Computer.getDefaultInstance();
        }
        computerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xu.netty.seventhexample.multimsg.proto.Computer, com.xu.netty.seventhexample.multimsg.proto.Computer.Builder, com.xu.netty.seventhexample.multimsg.proto.ComputerOrBuilder>(
                (com.xu.netty.seventhexample.multimsg.proto.Computer) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 4;
      onChanged();;
      return computerBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.xu.netty.seventhexample.multimsg.proto.MyMessage)
  }

  // @@protoc_insertion_point(class_scope:com.xu.netty.seventhexample.multimsg.proto.MyMessage)
  private static final com.xu.netty.seventhexample.multimsg.proto.MyMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xu.netty.seventhexample.multimsg.proto.MyMessage();
  }

  public static com.xu.netty.seventhexample.multimsg.proto.MyMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<MyMessage>
      PARSER = new com.google.protobuf.AbstractParser<MyMessage>() {
    @java.lang.Override
    public MyMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MyMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MyMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MyMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xu.netty.seventhexample.multimsg.proto.MyMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

